(() => {
'use strict';
const canvas = document.getElementById('game');
const ctx = canvas.getContext('2d');
const W = canvas.width, H = canvas.height;
const $ = id => document.getElementById(id);
const ui = {screen:$('screen'), start:$('start'), pause:$('pause'), wave:$('wave'), waveFill:$('waveFill'), score:$('score'), evade:$('evade'), hp:$('hpRow'), status:$('status')};
const keys = Object.create(null);
let state = 'title', last = 0, time = 0, shake = 0, flash = 0;
let bullets = [], particles = [], items = [], stars = [], emitters = [];
let wave = 1, waveTime = 0, waveDuration = 5.8, waveSpeedScale = 1, score = 0, evades = 0, nextItemAt = 55, highScore = +(localStorage.getItem('danmakuYokeroHigh') || 0);
let audioCtx = null;
const player = {x:W/2,y:H*.8,r:6,visualR:15,speed:275,hp:5,maxHp:5,hitInv:0,itemInv:0,trail:[]};
const pointer = {active:false,x:W/2,y:H*.8};
const joystick = {active:false,id:null,x:0,y:0};
let touchSlow = false;
const joyEl=$('joystick'), stickEl=$('stick'), slowBtn=$('slowBtn');
function rand(a,b){ return a + Math.random()*(b-a); }
function clamp(v,a,b){ return Math.max(a,Math.min(b,v)); }
function dist2(a,b,c,d){ const x=a-c,y=b-d; return x*x+y*y; }
function tone(freq=440,dur=.08,type='sine',gain=.025){try{if(!audioCtx) audioCtx = new (window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(), g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(gain,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+dur);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+dur);}catch(e){}}
function reset(){bullets=[];particles=[];items=[];emitters=[]; wave=1;waveTime=0;score=0;evades=0;nextItemAt=55;time=0;shake=0;flash=0;Object.assign(player,{x:W/2,y:H*.8,hp:5,hitInv:0,itemInv:0,trail:[]});state='playing';ui.screen.classList.add('hidden');ui.pause.textContent='Ⅱ';updateHud(); setupWave(); last=performance.now();}
function updateHud(){ui.wave.textContent=wave;ui.score.textContent=Math.floor(score).toLocaleString();ui.evade.textContent=evades;ui.waveFill.style.width=(waveTime/waveDuration*100)+'%';ui.hp.innerHTML='';for(let i=0;i<player.maxHp;i++){const s=document.createElement('span');s.className='heart'+(i>=player.hp?' off':'');s.textContent='♥';ui.hp.appendChild(s)}let st=''; if(player.itemInv>0) st=`無敵 ${player.itemInv.toFixed(1)}秒`; else if(player.hitInv>0) st='被弾後無敵';ui.status.textContent=st;}
function addParticle(x,y,color,count=8,speed=100){for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,s=rand(speed*.35,speed);particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:rand(.25,.7),max:.7,size:rand(1,4),color})}}
function bullet(x,y,vx,vy,r=5,color='#ff5476',kind='normal',extra={}){if(bullets.length>1650) return;bullets.push({x,y,vx,vy,r,color,kind,age:0,grazed:false,...extra});}
function variedSpeed(base, spread=.18){const roll=Math.random();let band=rand(1-spread,1+spread);if(roll<.12) band*=rand(.68,.84);else if(roll>.88) band*=rand(1.18,1.42);return base*band;}
function aimed(x,y,speed,spread=0,color='#ff5476',r=5,speedSpread=.18){const a=Math.atan2(player.y-y,player.x-x)+spread;const s=variedSpeed(speed,speedSpread);bullet(x,y,Math.cos(a)*s,Math.sin(a)*s,r,color);}
function radial(x,y,count,speed,offset=0,color='#ff8b4e',r=5,speedSpread=.24){for(let i=0;i<count;i++){const a=offset+i*Math.PI*2/count,s=variedSpeed(speed,speedSpread);bullet(x,y,Math.cos(a)*s,Math.sin(a)*s,r,color);}}
function emitterCountForWave(w){if(w<=3)return 1;if(w<=8)return 2;if(w<=15)return 3;if(w<=25)return 4;if(w<=40)return 5;if(w<=60)return 6;return 7;}
function randomEmitterPosition(existing){let chosen=null;for(let attempt=0;attempt<28;attempt++){const sideChance=wave<8?0:Math.min(.5,.12+wave*.0045);const edge=Math.random()<sideChance;let x,y;if(edge){x=Math.random()<.5?28:W-28;y=rand(90,Math.min(H*.58,165+wave*3.2));}else{x=rand(55,W-55);y=rand(48,wave>=30?145:112);}chosen={x,y,edge};if(existing.every(e=>dist2(x,y,e.x,e.y)>105*105))break;}return chosen;}
function setupWave(){emitters=[];waveDuration=wave%10===0?7.8:5.8;const roll=Math.random();waveSpeedScale=roll<.11?rand(.76,.88):roll>.89?rand(1.17,1.34):rand(.92,1.1);const count=emitterCountForWave(wave);for(let i=0;i<count;i++){const pos=randomEmitterPosition(emitters);emitters.push({...pos,phase:Math.random()*10,t:rand(0,.16),speedBias:rand(.84,1.18),intervalBias:rand(.88,1.12),drift:rand(18,42)});}if(wave%10===0){flash=.35;tone(150,.3,'sawtooth',.05)}}
function spawnPatterns(dt){const lv=wave;const baseSpeed=(100+lv*1.25)*waveSpeedScale;const interval=Math.max(.065,.345-lv*.00225);for(const e of emitters){e.t-=dt;e.phase+=dt;if(e.edge){e.y+=Math.sin(e.phase*.8)*e.drift*dt;}else{e.x+=Math.sin(e.phase*(.7+lv*.006))*e.drift*dt;e.x=clamp(e.x,45,W-45);}if(e.t>0)continue;e.t=interval*e.intervalBias*rand(.72,1.18)*(wave%10===0?.72:1);const burstSpeed=baseSpeed*e.speedBias*rand(.84,1.16);const patternCount=Math.min(6,1+Math.floor((lv+4)/8));const mode=(Math.floor(time*1.45)+Math.floor(e.phase*2.2)+Math.floor(lv/4))%patternCount;if(mode===0){const n=1+Math.floor(lv/14);for(let j=0;j<n;j++)aimed(e.x,e.y,burstSpeed*1.22,(j-(n-1)/2)*.11,'#ff5079',5,.2);}else if(mode===1){const n=8+Math.floor(lv/7);radial(e.x,e.y,n,burstSpeed*.74,e.phase,'#ff9e52',4.5,.28);}else if(mode===2){const a=e.phase*2.1;for(const side of [-1,1]){const s=variedSpeed(burstSpeed,.24);bullet(e.x,e.y,Math.cos(a*side)*s,Math.sin(a*side)*s,4.8,'#b76cff');}}else if(mode===3){const cols=2+Math.floor(lv/20);for(let j=0;j<cols;j++){const x=(e.x+j*83+time*92)%W,s=variedSpeed(burstSpeed*.9,.25);bullet(x,-8,Math.sin(time+j)*34,s,5.5,'#52d9ff');}}else if(mode===4){const n=3+Math.floor(lv/18);for(let j=0;j<n;j++){const a=Math.PI/2+(j-(n-1)/2)*.22+Math.sin(time*.8)*.18,s=variedSpeed(burstSpeed*1.03,.22);bullet(e.x,e.y,Math.cos(a)*s,Math.sin(a)*s,5,'#73ff9e');}}else{const a=Math.atan2(player.y-e.y,player.x-e.x);for(let j=-1;j<=1;j++){const s=variedSpeed(burstSpeed*.78,.27);bullet(e.x,e.y,Math.cos(a+j*.22)*s,Math.sin(a+j*.22)*s,6,'#fff06a','curve',{turn:j*.42*(Math.random()>.5?1:-1)});}}}if(lv>=24&&Math.random()<dt*(.25+lv*.0045)){const side=Math.random()<.5?-1:1,y=rand(100,H*.65),s=variedSpeed(baseSpeed*1.05,.22);bullet(side<0?-10:W+10,y,-side*s,rand(-25,25),7,'#ff4fd8','wall');}if(lv>=48&&Math.random()<dt*(.1+lv*.0023)){const x=rand(30,W-30);aimed(x,-8,baseSpeed*.55,0,'#ffffff',8,.3);}}
function spawnItem(){const needHeal=player.hp<=2;const type=needHeal||Math.random()<.48?'heal':'inv';items.push({x:rand(90,W-90),y:-25,vy:72,type,r:14,age:0});tone(type==='heal'?660:880,.16,'triangle',.035);}
function hitPlayer(){if(player.hitInv>0||player.itemInv>0||state!=='playing') return;player.hp--;player.hitInv=1.25;shake=12;flash=.17;addParticle(player.x,player.y,'#ff4772',22,190);tone(90,.22,'square',.055);if(player.hp<=0) endGame(false);}
function endGame(clear){state=clear?'clear':'gameover';const total=Math.floor(score+(clear?100000:0));score=total;if(total>highScore){highScore=total;localStorage.setItem('danmakuYokeroHigh',highScore)}ui.screen.classList.remove('hidden');ui.screen.innerHTML=`<div class="card"><h1 style="font-size:clamp(32px,6vw,62px)">${clear?'ALL CLEAR!':'GAME OVER'}</h1><div class="subtitle">${clear?'100 WAVES COMPLETE':'WAVE '+wave}</div><div style="font-size:32px;font-weight:900;margin:14px 0">${total.toLocaleString()} pts</div><div style="color:#9fc5d9;margin-bottom:20px">回避数 ${evades.toLocaleString()}　／　BEST ${highScore.toLocaleString()}</div><button id="retry">RETRY</button><div class="small">${clear?'弾幕を完全制覇しました。':'弾の中心ではなく、隙間の流れを見ると避けやすくなります。'}</div></div>`;document.getElementById('retry').onclick=reset;tone(clear?740:120,.45,clear?'triangle':'sawtooth',.05);}
function togglePause(){if(state==='playing'){state='paused';ui.pause.textContent='▶';ui.screen.classList.remove('hidden');ui.screen.innerHTML='<div class="card"><h1 style="font-size:48px">PAUSE</h1><div class="subtitle">ひと休み</div><button id="resume">RESUME</button></div>';document.getElementById('resume').onclick=togglePause;}else if(state==='paused'){state='playing';ui.pause.textContent='Ⅱ';ui.screen.classList.add('hidden');last=performance.now()}}
function update(dt){time+=dt;waveTime+=dt;score+=dt*(100+wave*8);player.hitInv=Math.max(0,player.hitInv-dt);player.itemInv=Math.max(0,player.itemInv-dt);shake*=Math.pow(.001,dt);flash=Math.max(0,flash-dt);let dx=(keys.ArrowRight||keys.KeyD?1:0)-(keys.ArrowLeft||keys.KeyA?1:0);let dy=(keys.ArrowDown||keys.KeyS?1:0)-(keys.ArrowUp||keys.KeyW?1:0);const slow=keys.ShiftLeft||keys.ShiftRight||touchSlow;if(joystick.active){dx=joystick.x;dy=joystick.y;const d=Math.hypot(dx,dy);if(d>.08){player.x+=dx*player.speed*(slow?.46:1)*dt;player.y+=dy*player.speed*(slow?.46:1)*dt}}else if(pointer.active){const px=pointer.x-player.x,py=pointer.y-player.y,d=Math.hypot(px,py);if(d>3){dx=px/d;dy=py/d;player.x+=dx*Math.min(d,player.speed*dt*.9);player.y+=dy*Math.min(d,player.speed*dt*.9)}}else if(dx||dy){const d=Math.hypot(dx,dy);player.x+=dx/d*player.speed*(slow?.46:1)*dt;player.y+=dy/d*player.speed*(slow?.46:1)*dt}player.x=clamp(player.x,22,W-22);player.y=clamp(player.y,35,H-22);player.trail.unshift({x:player.x,y:player.y});if(player.trail.length>10)player.trail.pop();spawnPatterns(dt);for(let i=bullets.length-1;i>=0;i--){const b=bullets[i];b.age+=dt;if(b.kind==='curve'){const a=Math.atan2(b.vy,b.vx)+b.turn*dt;b.vx=Math.cos(a)*Math.hypot(b.vx,b.vy);b.vy=Math.sin(a)*Math.hypot(b.vx,b.vy)}b.x+=b.vx*dt;b.y+=b.vy*dt;const d2=dist2(b.x,b.y,player.x,player.y), hit=(b.r+player.r)**2, graze=(b.r+28)**2;if(d2<hit){bullets.splice(i,1);hitPlayer();continue}if(!b.grazed&&d2<graze){b.grazed=true;evades++;score+=35+wave*2;addParticle(b.x,b.y,'#c9f7ff',3,42);if(evades>=nextItemAt){spawnItem();nextItemAt+=Math.max(35,60-Math.floor(wave/4))}}if(b.x<-60||b.x>W+60||b.y<-80||b.y>H+80) bullets.splice(i,1);}for(let i=items.length-1;i>=0;i--){const it=items[i];it.age+=dt;it.y+=it.vy*dt;it.x+=Math.sin(it.age*3)*20*dt;if(dist2(it.x,it.y,player.x,player.y)<(it.r+player.visualR)**2){if(it.type==='heal'){player.hp=Math.min(player.maxHp,player.hp+1);addParticle(it.x,it.y,'#65ffb0',18,130);tone(720,.2,'sine',.04)}else{player.itemInv=Math.max(player.itemInv,5.5);addParticle(it.x,it.y,'#76eaff',25,150);tone(980,.25,'triangle',.04)}score+=800;items.splice(i,1);continue;}if(it.y>H+30)items.splice(i,1);}for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=Math.pow(.05,dt);p.vy*=Math.pow(.05,dt);if(p.life<=0)particles.splice(i,1)}if(waveTime>=waveDuration){waveTime=0;if(wave>=100){endGame(true);return}wave++;score+=wave*120;setupWave();tone(330+wave*3,.08,'triangle',.02)}updateHud();}
function drawBackground(){const g=ctx.createRadialGradient(W*.5,H*.55,20,W*.5,H*.55,H*.85);g.addColorStop(0,'#102044');g.addColorStop(.48,'#071126');g.addColorStop(1,'#02040b');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.save();ctx.globalAlpha=.18;ctx.strokeStyle='#4d8ec5';ctx.lineWidth=1;const off=(time*14)%40;for(let y=-40+off;y<H;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}for(let x=0;x<W;x+=60){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}ctx.restore();for(const s of stars){s.y+=s.s*(state==='playing'?1:.15);if(s.y>H){s.y=-2;s.x=Math.random()*W}ctx.globalAlpha=s.a;ctx.fillStyle='#bdeaff';ctx.fillRect(s.x,s.y,s.r,s.r)}ctx.globalAlpha=1;}
function draw(){ctx.save();if(shake>.5)ctx.translate(rand(-shake,shake),rand(-shake,shake));drawBackground();for(const e of emitters){ctx.save();ctx.translate(e.x,e.y);ctx.rotate(time*.5);ctx.strokeStyle='rgba(255,110,170,.45)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,17,0,Math.PI*2);ctx.stroke();for(let i=0;i<4;i++){ctx.rotate(Math.PI/2);ctx.fillStyle='rgba(255,90,140,.45)';ctx.fillRect(18,-2,8,4)}ctx.restore()}for(const b of bullets){ctx.save();ctx.translate(b.x,b.y);const glow=ctx.createRadialGradient(0,0,0,0,0,b.r*2.5);glow.addColorStop(0,'#fff');glow.addColorStop(.26,b.color);glow.addColorStop(1,'transparent');ctx.fillStyle=glow;ctx.beginPath();ctx.arc(0,0,b.r*2.5,0,Math.PI*2);ctx.fill();ctx.fillStyle=b.color;ctx.beginPath();ctx.arc(0,0,b.r,0,Math.PI*2);ctx.fill();ctx.restore()}for(const it of items){ctx.save();ctx.translate(it.x,it.y);ctx.rotate(Math.sin(it.age*2)*.15);ctx.shadowBlur=18;ctx.shadowColor=it.type==='heal'?'#65ffb0':'#72e9ff';ctx.fillStyle=it.type==='heal'?'#65ffb0':'#72e9ff';ctx.beginPath();ctx.arc(0,0,it.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#052033';ctx.font='bold 18px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(it.type==='heal'?'+':'◇',0,1);ctx.restore()}for(const p of particles){ctx.globalAlpha=clamp(p.life/p.max,0,1);ctx.fillStyle=p.color;ctx.fillRect(p.x-p.size/2,p.y-p.size/2,p.size,p.size)}ctx.globalAlpha=1;const inv=player.itemInv>0, flicker=player.hitInv>0&&Math.floor(time*18)%2===0;if(!flicker){for(let i=player.trail.length-1;i>0;i--){const t=player.trail[i];ctx.globalAlpha=(1-i/player.trail.length)*.18;ctx.fillStyle=inv?'#72e9ff':'#6e88ff';ctx.beginPath();ctx.arc(t.x,t.y,player.visualR*(1-i/player.trail.length),0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;ctx.save();ctx.translate(player.x,player.y);if(inv){ctx.strokeStyle='#8ff7ff';ctx.lineWidth=3;ctx.globalAlpha=.55+.35*Math.sin(time*9);ctx.beginPath();ctx.arc(0,0,25+Math.sin(time*7)*3,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1}ctx.rotate(Math.PI/4);ctx.shadowBlur=18;ctx.shadowColor=inv?'#65f5ff':'#7b8cff';ctx.fillStyle=inv?'#d8ffff':'#e5e8ff';ctx.fillRect(-9,-9,18,18);ctx.shadowBlur=0;ctx.fillStyle='#253b8f';ctx.fillRect(-4,-4,8,8);ctx.restore();ctx.fillStyle='#ff4f6f';ctx.beginPath();ctx.arc(player.x,player.y,player.r,0,Math.PI*2);ctx.fill();}if(wave%10===0&&state==='playing'){ctx.save();ctx.globalAlpha=.12+.05*Math.sin(time*5);ctx.fillStyle='#ff315e';ctx.fillRect(0,0,W,H);ctx.restore();ctx.fillStyle='rgba(255,255,255,.7)';ctx.font='900 16px sans-serif';ctx.textAlign='center';ctx.fillText('DANGER WAVE',W/2,137)}if(flash>0){ctx.globalAlpha=Math.min(.65,flash*3);ctx.fillStyle='#fff';ctx.fillRect(0,0,W,H);ctx.globalAlpha=1}ctx.restore();}
function loop(now){const dt=Math.min(.034,(now-last)/1000||0);last=now;if(state==='playing')update(dt);draw();requestAnimationFrame(loop)}
function canvasPos(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height}}
window.addEventListener('keydown',e=>{keys[e.code]=true;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();if(e.code==='KeyP'||e.code==='Escape')togglePause()},{passive:false});
window.addEventListener('keyup',e=>keys[e.code]=false);
canvas.addEventListener('pointerdown',e=>{if(state!=='playing'||e.pointerType==='touch')return;pointer.active=true;const p=canvasPos(e);pointer.x=p.x;pointer.y=p.y;canvas.setPointerCapture(e.pointerId)});
canvas.addEventListener('pointermove',e=>{if(!pointer.active)return;const p=canvasPos(e);pointer.x=p.x;pointer.y=p.y});
canvas.addEventListener('pointerup',()=>pointer.active=false);canvas.addEventListener('pointercancel',()=>pointer.active=false);
function setJoystick(e){const r=joyEl.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2;let x=e.clientX-cx,y=e.clientY-cy;const max=r.width*.33,d=Math.hypot(x,y)||1;if(d>max){x=x/d*max;y=y/d*max}joystick.x=x/max;joystick.y=y/max;stickEl.style.transform=`translate(${x}px,${y}px)`}
function releaseJoystick(e){if(e&&joystick.id!==null&&e.pointerId!==joystick.id)return;joystick.active=false;joystick.id=null;joystick.x=joystick.y=0;stickEl.style.transform='translate(0,0)'}
joyEl.addEventListener('pointerdown',e=>{if(state!=='playing')return;joystick.active=true;joystick.id=e.pointerId;joyEl.setPointerCapture(e.pointerId);setJoystick(e);e.preventDefault()});
joyEl.addEventListener('pointermove',e=>{if(joystick.active&&e.pointerId===joystick.id){setJoystick(e);e.preventDefault()}});
joyEl.addEventListener('pointerup',releaseJoystick);joyEl.addEventListener('pointercancel',releaseJoystick);
slowBtn.addEventListener('pointerdown',e=>{touchSlow=true;slowBtn.classList.add('active');slowBtn.setPointerCapture(e.pointerId);e.preventDefault()});
const releaseSlow=()=>{touchSlow=false;slowBtn.classList.remove('active')};slowBtn.addEventListener('pointerup',releaseSlow);slowBtn.addEventListener('pointercancel',releaseSlow);
ui.start.onclick=reset;ui.pause.onclick=togglePause;
for(let i=0;i<95;i++)stars.push({x:Math.random()*W,y:Math.random()*H,s:rand(.12,.7),a:rand(.15,.75),r:Math.random()<.12?2:1});
updateHud();requestAnimationFrame(loop);
})();